### ISSUE TITLE
Null pointer exception when I view my local projects

### ISSUE THREAD

**Issue by shapun963** [Iyxan23/sk-collab#18]
Some of my files in /mysc/list/id/project  are  corrupted so add try catch on recyclerview bind
or check if  map contains the key before getting data from the key .
Sorry for the bad english.

**Comment by Iyxan23** [comment]
Can you provide a screenshot of the error?

**Comment by Iyxan23** [comment]
In my opinion, getting data using a key from a JSONObject will **require** a `try` block to suppress the JSONException, so every operation with JSONObject should have a `try` block around it.

If that's the case (project corruption), according to this code snippet in [SketchwareProjectAdapter](https://github.com/Iyxan23/sk-collab/tree/main/app/src/main/java/com/iyxan23/sketch/collab/adapters/SketchwareProjectAdapter.java):

https://github.com/Iyxan23/sk-collab/blob/4a2b9e8c58dc74e3697b4a813d07c072d12b0457/app/src/main/java/com/iyxan23/sketch/collab/adapters/SketchwareProjectAdapter.java#L79-L82

It should continue to work fine and toast an error message instead of crashing.

**Comment by shapun963** [comment]
![Uploading Screenshot_20210201-172817~2.png…]()

**Comment by Iyxan23** [comment]
You should wait for the picture to be uploaded before sending the comment :hidepain:

**Comment by shapun963** [comment]
![Screenshot_20210201-172817~2.png](https://user-images.githubusercontent.com/71916205/106457854-9a913d80-64b5-11eb-8215-f53fc0d07344.png)

**Comment by shapun963** [comment]
I think I edited app_name and changed it to something else :hidepain:

**Comment by Iyxan23** [comment]
hidepain the app_name key doesn't exist, I think i should add a detection for a corrupted sketchware project

**Comment by Iyxan23** [comment]
Oh no i don't need to, i can just check if it's null

**Comment by Iyxan23** [comment]
Alright the issue is solved, Thanks for reporting.
